default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: redmine_develop

test:
  <<: *default
  database: redmine_test

production:
  <<: *default
  database: redmine_production
